name: Nightly TICS scan

on:
  schedule:
    - cron: '09 23 * * *' # Every day at 23:09 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  TICS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install requirements
        run: |
          sudo apt update -y
          sudo apt install python3-venv -y

      - name: Create and activate virtual environment
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install tox pylint flake8
          pip install --requirement requirements.txt
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Run coverage tests
        run: |
          tox -e unit

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: cephfs-server-proxy-operator
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          branchdir: ${{ env.GITHUB_WORKSPACE }}
          ticsAuthToken: ${{ secrets.TICS_AUTH_TOKEN }}
          installTics: true
          calc: ALL
